workflows:
  build-android-app:
    name: Build Android APK
    max_build_duration: 15
    environment:
      java: 17
    scripts:
      - echo "Starting build..."
      - chmod +x gradlew
      - ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - your.email@example.com
