workflows:
  android-native-build:
    name: Build Native Android APK
    instance_type: mac_mini_m1
    environment:
      java: 11
    scripts:
      - name: Set execute permission for gradlew
        script: | 
          chmod +x gradlew
      - name: Build debug APK
        script: | 
          ./gradlew assembleDebug
    artifacts:
      - build/outputs/apk/debug/*.apk
