workflows:
  build-android-app:
    name: Build Android APK
    max_build_duration: 15
    environment:
      java: 17
    scripts:
      - echo "Starting build..."
      - chmod +x gradlew
      - ./gradlew clean assembleDebug
    artifacts:
      - aartifacts:
  - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - adm.shadoww@gmail.com
